/**
 * The only place themed display strings live. Code uses neutral names (ADR-0002); the ui asks
 * `term(key)` for what to show. Vocabulary from the station runtime brief §4 (ADR-0010): keys are
 * the neutral code identifiers, values are what the Commander reads. These words are another
 * product's vocabulary; revisit before a public release.
 * Health and run words, read/write, and every `.plain` entry stay plain.
 */
export const glossary = {
  station: "Station",
  "station.plain": "station",
  user: "Commander",
  "user.plain": "you",
  room: "Room",
  rooms: "Rooms",
  "room.plain": "team",
  "room.verb": "Add room",
  agent: "Crew member",
  agents: "Crew",
  "agent.plain": "agent",
  "agent.verb": "Add crew member",
  overseer: "the Overseer",
  "overseer.plain": "overseer",
  "overseer.role": "Overseer",
  lane: "Hallway",
  lanes: "Hallways",
  "lane.plain": "handoff lane",
  "lane.verb": "Open hallway",
  "lane.close": "Close",
  grant: "Prop",
  grants: "Props",
  "grant.plain": "capability grant",
  "grant.verb": "Place prop",
  "grant.revoke": "Remove",
  "grant.read": "read",
  "grant.write": "write",
  connector: "Connector",
  connectors: "Connectors",
  "connector.plain": "MCP server",
  comms: "COMMS",
  "comms.plain": "chat",
  session: "Session",
  sessions: "Sessions",
  run: "Run",
  runs: "Runs",
  "run.plain": "run",
  "run.last": "last run",
  dispatch: "Dispatch",
  "dispatch.plain": "delegated task",
  approvalMode: "Approval mode",
  "approvalMode.ask": "Ask first",
  "approvalMode.full": "Full power",
  memory: "Memory",
  "memory.beliefs": "Stored beliefs",
  "memory.proposals": "Awaiting your decision",
  notifications: "Notifications",
  settings: "Settings",
  "connection.connecting": "connecting",
  "connection.connected": "live",
  "connection.reconnecting": "reconnecting",
  "connection.unauthorized": "not authorized",
  "connection.closed": "offline",
  "events.latest": "Latest event",
  "events.recent": "Recent events",
  "empty.events.title": "Nothing has happened yet",
  "empty.events.body": "Events appear here as the runtime records them.",
  "empty.phase.title": "Not built yet",
  "approvalMode.ask.hint": "Tool calls that change something wait for your approval.",
  "approvalMode.full.hint":
    "Runs every tool without asking, including ones that change things. Use with care.",
  "prop.web": "Web",
  "prop.files": "Files",
  "prop.memory": "Memory",
  "tools.effective": "What this crew member can use",
  "tools.none": "Nothing yet. Place props in this crew member's room, or grant a connector.",
  "tools.source.role": "role",
  "tools.connector.pending": "is granted; its tools appear here once it is connected.",
  "empty.crew.title": "No crew yet",
  "empty.crew.body": "Add a crew member to a room to get started.",
  "empty.station.title": "No station yet",
  "empty.station.body": "This station directory has no valid station.json. Onboarding creates one.",
  "comms.sessions": "Sessions",
  "comms.new": "New session",
  "comms.open": "Open",
  "comms.close": "Close",
  "comms.send": "Send",
  "comms.cancel": "Cancel",
  "comms.archive": "Archive",
  "comms.placeholder": "Message",
  "comms.pick.title": "Pick a crew member",
  "comms.pick.body": "Choose who to talk to, then open or start a session.",
  "comms.empty.title": "No messages yet",
  "comms.empty.body": "Say something to start.",
  "comms.none.title": "No sessions yet",
  "comms.none.body": "Start one to talk to this crew member.",
  "comms.tool.call": "used",
  "comms.tool.rejected": "was refused",
  "comms.tool.error": "failed",
  "comms.stepsLimit": "Stopped after the step limit.",
  "runState.queued": "queued",
  "runState.running": "responding",
  "runState.awaiting_consent": "waiting for your approval",
  "runState.completed": "done",
  "runState.failed": "failed",
  "runState.cancelled": "cancelled",
  "runState.interrupted": "interrupted: the daemon stopped mid-run",
  "runState.blocked_budget": "stopped by a budget",
  "settings.models": "Models",
  "settings.model.openrouter": "Runs use OpenRouter with your key.",
  "settings.model.fake":
    "Runs use the scripted fake model: canned replies, and nothing is sent to OpenRouter.",
  "settings.key": "OpenRouter key",
  "settings.key.none": "No key configured.",
  "settings.key.new": "New key",
  "settings.key.keychain": "Stored in your OS keychain.",
  "settings.key.env":
    "Read from OPENROUTER_API_KEY in the daemon's environment (development fallback).",
  "settings.key.save": "Check and save key",
  "settings.key.remove": "Remove stored key",
  "settings.key.hint":
    "The key is checked with OpenRouter, stored in your OS keychain, and never shown again.",
  "killSwitch.engage": "Stop everything",
  "killSwitch.clear": "Resume",
  "killSwitch.on": "Kill switch on: nothing runs until you resume.",
  "consent.title": "Approval needed",
  "consent.body": "wants to use",
  "consent.approve": "Approve",
  "consent.deny": "Deny",
  "consent.none.title": "Nothing needs your approval",
  "consent.none.body": "When a crew member on Ask first wants to change something, it waits here.",
  "spend.today": "Today",
  "spend.session": "Spent",
  "spend.unpriced": "some calls had no reported cost",
  "notifications.approvals": "Awaiting your approval",
  "document.identity": "Identity",
  "document.purpose": "Purpose",
  "document.standing-orders": "Standing orders",
  "document.context": "Context",
  "health.ok": "healthy",
  "health.attention": "needs attention",
  "health.stalled": "stalled",
  "run.idle": "idle",
  "run.working": "working",
  "run.done": "done",
  "run.failed": "failed",
  "overseer.idle": "idle",
  "overseer.reconciling": "reconciling",
  "overseer.reported": "reported",
  "overseer.attention": "needs attention",
  "empty.lanes.title": "No hallways",
  "empty.lanes.body": "Rooms can't hand work to each other until a hallway is opened between them.",
  "empty.runs.title": "No runs yet",
  "empty.runs.body": "Nothing has run here yet.",
  "proof.asOf": "as of",
  "report.tab": "Report",
  "report.lastRun": "Last run",
  "report.runs": "Runs",
  "report.lanes": "Hallways",
  "report.agents": "Crew",
  // Milestone 1 (Routines ledger) terms, plain until their views are removed (ADR-0010, Phase 1).
  ledger: "Ledger",
  "ledger.plain": "ledger",
  "system.report": "Digest",
  "system.report.plain": "digest",
  "report.ledger": "Ledger",
  "empty.ledger.title": "No ledger yet",
  "empty.ledger.body": "Nothing has run here yet.",
} as const;

export type GlossaryKey = keyof typeof glossary;
export const GLOSSARY_KEYS = Object.keys(glossary) as GlossaryKey[];

/** Display string for a glossary key. */
export function term(key: GlossaryKey): string {
  return glossary[key];
}
