import { SCHEMA_VERSION, type Station } from "@darthsaul/outerworld-ai-core";
import type { EmittedFile } from "./files.js";
import { statusContract } from "./files.js";
import { grantLabel, json, scheduleLabel, table, teamById } from "./text.js";

export function emitClaudeMd(station: Station, generatedAt: string): EmittedFile {
  const name = (id: string) => teamById(station, id)?.name ?? id;
  const teamRows = station.teams.map((t) => [
    `${t.name} (\`${t.id}\`)`,
    t.mission,
    scheduleLabel(t.schedule),
    station.agents
      .filter((a) => a.teamId === t.id)
      .map((a) => a.persona.name)
      .join(", ") || "none",
  ]);
  const grantRows = station.grants.map((g) => [name(g.teamId), `\`${g.id}\``, grantLabel(g)]);
  const handoffRows = station.handoffs.map((h) => [
    `\`${h.from}\` (${name(h.from)})`,
    "→",
    `\`${h.to}\` (${name(h.to)})`,
    `\`ledger/${h.from}.md\``,
    h.note ?? "",
  ]);
  const c = statusContract();
  const contents = `# ${station.name} · ledger repo

Generated by Outerworld AI on ${generatedAt} from \`station.json\` (schema version ${SCHEMA_VERSION}).
Regenerate with \`outerworld generate --station station.json --out .\`; personas, skills,
prompts, this file, and the digest script are rewritten, while station reports and \`status/\`
are never overwritten without \`--force\`.

## What this repository is

The shared memory of a set of Claude Code Routines. Each station is one Routine that clones this
repo, reads its station report and the reports it is allowed to read, does its mission, updates
its report, writes status files, and commits. The overseer (${station.overseer.persona.name}) reads
everything, writes the System Report, and posts it to Discord. A Routine starts with zero
context: if it is not in this repo, it does not exist.

## Stations

${table(["station", "mission", "schedule", "agents"], teamRows)}

Prompts: \`routines/<teamId>.prompt.md\` and \`routines/overseer.prompt.md\`. Personas:
\`agents/<agentId>.md\`.

## Tools (grants)

${table(["station", "grant", "tool"], grantRows)}

Grants are enforced by these prompts, not by the platform. A station uses only its grants.

## Handoffs (who may read whose station report)

${table(["writer", "", "reader", "file", "note"], handoffRows)}

A handoff is read authorization only. Nobody edits another station's report.

## Station reports

\`ledger/<teamId>.md\`, each with a marker line and exactly three sections the dashboard parses:
\`## Next steps\`, \`## Waiting on\`, \`## Log\`.

## Status contract

Every Routine writes \`status/runs/<teamId>/<startedAt>.json\` (opened at the start, closed at
the end) and \`status/teams/<teamId>.json\`; the overseer writes \`status/overseer.json\` and
\`status/digest.md\`. Shapes:

${json(c.run)}

${json(c.team)}

## Rules for every Routine

1. Read \`CLAUDE.md\`, your prompt, and your personas before acting.
2. Use only your grants. Read access is read only.
3. Never edit another station's report. Never write \`status/\` files other than your own.
4. Never assert a state you did not reach; write \`failed\` with an \`error\` when something broke.
5. Commit with a conventional message and push to the default branch: check out the default branch first,
   since the session starts on a \`claude/\` branch (\`claude/status\` only if the push is rejected).
6. Never commit a secret. The Discord webhook URL lives only in the overseer's environment.
`;
  return { path: "CLAUDE.md", contents };
}
